name: Build Linux and macOS package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  package:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run package task
        run: ./gradlew --no-daemon minify generateMainDatabaseSchema
      - name: Collect artifacts
        run: |
          mkdir build/artifacts
          mv build/compose/jars/*.min.jar build/artifacts/
          mv build/schemas/1.db build/artifacts/scheduler.db
          sqlite3 build/artifacts/scheduler.db 'PRAGMA user_version = 1;'
          sqlite3 build/artifacts/scheduler.db < sample_data.sql
      - uses: actions/upload-artifact@v2
        with:
          name: scheduler-${{ runner.os }}
          path: |
            build/artifacts/*