name: Build Linux package

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 15
      - name: Setup Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run package task
        run: ./gradlew --no-daemon --info packageUberJarForCurrentOS packageAppImage
      - name: Collect artifacts
        run: |
          mkdir build/artifacts
          mv build/compose/jars/* build/artifacts/
          mv build/compose/binaries/main/app/* build/artifacts/
      - uses: actions/upload-artifact@v2
        with:
          name: scheduler
          path: |
            build/artifacts/*