name: Build Windows package

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: windows-2019
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Install sqlite3
        run: choco install sqlite
      - name: Run package task
        run: .\gradlew.bat --no-daemon minify packageExe generateMainDatabaseSchema
      - name: Collect artifacts
        run: |
          mkdir build\artifacts
          move build\compose\jars\*.min.jar build\artifacts\
          move build\compose\binaries\main\exe\* build\artifacts\
          move build\schemas\1.db build\artifacts\scheduler.db
          sqlite3.exe build\artifacts\scheduler.db 'PRAGMA user_version = 1;'
          Get-Content sample_data.sql | sqlite3.exe build\artifacts\scheduler.db
      - uses: actions/upload-artifact@v2
        with:
          name: scheduler-${{ runner.os }}
          path: |
            build\artifacts\*